version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
